version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - "20717:20717"
  megasena-server:
    image: megasena-server:1.0
    container_name: megasena-server
    ports:
      - "8080:8080"
    links:
      - mongodb
